# Welcome to Jekyll!
#

# Site settings
title: davecollins.org
description:
owner: Dave Collins # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: collins.180@osu.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/cmhdave73
  github: https://github.com/cmhdave
  linkedin-square: https://linkedin.com/in/cmhdave
  facebook-official: https://facebook.com/cmhdave73
  google-plus-square: https://plus.google.com/u/0/+DaveCollins73
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  stackexchange: https://stackexchange.com/users/1310126/davec
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed